name: Db Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true   # Push the Docker image
        tags: user/app:latest  # Tags for the Docker image

        # If you have a Dockerfile in a different directory, adjust the context accordingly
        # context: ./path/to/your/directory

        # Additional build arguments can be specified if needed
        # build-args: '--build-arg FOO=bar'
